# Generated by Django 5.2.3 on 2025-06-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('product_type', models.CharField(choices=[('CD', 'CD'), ('MERCH', 'Merchandise'), ('DIGITAL', 'Digital Download'), ('SHIRTS', 'Shirts'), ('HYMNBOOKS', 'Hymn Books'), ('NOTEBOOKS', 'Notebooks'), ('UMBRELLAS', 'Umbrellas')], default='CD', max_length=20)),
                ('digital_file', models.FileField(blank=True, help_text='For digital downloads only', null=True, upload_to='digital_products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
