# Generated by Django 5.2.3 on 2025-06-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_galleryimage_delete_gallery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='category',
            field=models.CharField(choices=[('worship', 'Worship'), ('events', 'Events'), ('mission', 'Mission'), ('gatetogether', 'Gate to Gather'), ('fellowship', 'Fellowship'), ('lunch_hour', 'Lunch Hour'), ('behind_the_scenes', 'Behind the Scenes')], default='worship', max_length=50),
        ),
    ]
