# Generated by Django 5.2.3 on 2025-06-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_teammember_whatsapp_link_teammember_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='email_link',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='linkedin_link',
        ),
        migrations.AddField(
            model_name='teammember',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='teammember',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
    ]
